language: node_js
node_js:
  - "8"

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE gothencupdb;'

jobs:
  include:
    - stage: deploy client production
      script:
        - cd client && npm install
        - npm run build
        - cd -
