language: node_js
node_js:
  - "8"
services:
  - mysql
before_install:
  - mysql -u root -e 'CREATE DATABASE testbase;'
  - mysql -e 'use gothencupdb_test;'
  - mysql -e 'source sql/create.sql;'
  - mysql -e 'source sql/insert.sql;'
jobs:
  include:
    - stage: deploy client production
      script:
        - cd client && npm install
        - npm run build
        - cd -
