language: node_js
node_js:
  - "8"
jobs:
  include:
    - stage: deploy client production
      script:
        - cd client && npm install
        - npm run build
        - cd -
    - stage: deploy api production
      script:
        - cd api && npm install
        - npm run all
        - cd -
