language: node_js
node_js:
  - "8"
jobs:
  include:
    - stage: deploy client production
      script:
        - cd client && npm install && cd -
        - npm run build:client
    - stage: deploy api production
      script:
        - cd api && npm install && cd -
        - npm run build:api
