language: node_js
node_js:
  - "8"
services:
  - mysql
before_install:
  - mysql -u root -e 'CREATE DATABASE gothencupdb_test;'
  - mysql -u root gothencupdb_test < sql/create.sql
  - mysql -u root gothencupdb_test < sql/insert.sql

jobs:
  include:
    - stage: deploy client production
      script:
        - cd client && npm install
        - npm run build
        - cd api && npm install
        - npm test
